theme: jekyll-theme-cayman
title: Blog by M. Boerma
description: A website containing a personal blog posts and a collection of links to interesting articles.
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
