theme: jekyll-theme-cayman
title: Blog by M. Boerma
description: A website containing personal blog posts and a collection of articles on certain topics found around the Internet that I like.
show_downloads: "false"
google_analytics: [Your Google Analytics tracking ID]
