theme: minima
title: Blog by M. Boerma
description: A website containing a personal blog posts and a collection of links to interesting articles.
google_analytics: [Your Google Analytics tracking ID]
disqus:
   shortname: mboerma
